# Generated by Django 3.2.4 on 2021-06-30 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiants',
            fields=[
                ('IDetudiant', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=64)),
                ('prenom', models.CharField(max_length=64)),
                ('numTeleph', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('TypeSS', models.CharField(max_length=64)),
                ('inscrit', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Fiches',
            fields=[
                ('noFiche', models.AutoField(primary_key=True, serialize=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.etudiants')),
            ],
        ),
    ]
