# Generated by Django 3.2.5 on 2021-07-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuteur',
            name='stage',
            field=models.CharField(default='hello', max_length=64),
        ),
    ]
