# Generated by Django 3.2.4 on 2021-06-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiants',
            name='TypeSS',
            field=models.CharField(choices=[('1', 'Ayant Droit'), ('2', 'Etudiant'), ('3', 'Assuré Volontaire'), ('4', 'Etudiant Etranger')], max_length=64),
        ),
    ]
