# Generated by Django 3.2.5 on 2021-07-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tuteur_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuteur',
            name='stage',
        ),
    ]
