# Generated by Django 3.2.4 on 2021-06-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_etudiants_typess'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etudiants',
            new_name='Etudiant',
        ),
        migrations.RenameModel(
            old_name='Fiches',
            new_name='Fiche',
        ),
    ]
