# Generated by Django 3.2.5 on 2021-07-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_tuteur_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='tuteur',
        ),
        migrations.AlterField(
            model_name='date',
            name='date_interuption_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='date_interuption_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
