# Generated by Django 3.2.4 on 2021-06-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210630_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='IDetudiant',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
