# Generated by Django 3.2.4 on 2021-06-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_etudiant_idetudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='IDetudiant',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
