# Generated by Django 3.2.5 on 2021-07-01 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210701_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='tuteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tuteur_stage', to='api.tuteur'),
        ),
    ]
