# Generated by Django 3.2.4 on 2021-06-30 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_etudiant_idetudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to='api.etudiant'),
        ),
    ]
