# Generated by Django 3.2.5 on 2021-07-01 10:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_stage_tuteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='adresse_etud',
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='codeAPE',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='noSiret',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.MinLengthValidator(14)]),
        ),
        migrations.AlterField(
            model_name='stage',
            name='gratification_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gratification_stage', to='api.gratification'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='tuteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuteur_stage', to='api.tuteur'),
        ),
    ]
