# Generated by Django 3.2.4 on 2021-06-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_fiche_etudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='TypeSS',
            field=models.CharField(choices=[('Ayant Droit', 'Ayant Droit'), ('Etudiant', 'Etudiant'), ('Assuré Volontaire', 'Assuré Volontaire'), ('Etudiant Etranger', 'Etudiant Etranger')], max_length=64),
        ),
    ]
