# Generated by Django 3.2.5 on 2021-07-01 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210701_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='adresse_etud',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adresse_etud', to='api.adresse'),
        ),
    ]
