# Generated by Django 3.2.4 on 2021-07-02 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_etudiant_adresse_etud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='adresse_etud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adresse_etud', to='api.adresse'),
        ),
    ]
