# Generated by Django 3.2.4 on 2021-06-30 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_etudiant_idetudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='CAM',
            field=models.CharField(choices=[('CPAM', 'CPAM'), ('MSA', 'MSA'), ('Travailleur indépendant', 'Travailleur indépendant'), ('régimes spéciaux', 'régimes spéciaux')], default='CPAM', max_length=64),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='enseingnant',
            field=models.CharField(default='Laurence Pierre', max_length=64),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='IDetudiant',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
