# Generated by Django 3.2.4 on 2021-07-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_etudiant_adresse_etud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etablissement',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='adresse_etud',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='rhservice',
            name='adresse_RH',
        ),
        migrations.RemoveField(
            model_name='rhservice',
            name='etab_RH',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='IDetudiant',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='gratification_detail',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='tuteur',
        ),
        migrations.RemoveField(
            model_name='tuteur',
            name='adresse_Tuteur',
        ),
        migrations.RemoveField(
            model_name='tuteur',
            name='etab',
        ),
        migrations.DeleteModel(
            name='Accueilservice',
        ),
        migrations.DeleteModel(
            name='Adresse',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='Etablissement',
        ),
        migrations.DeleteModel(
            name='Etudiant',
        ),
        migrations.DeleteModel(
            name='Fiche',
        ),
        migrations.DeleteModel(
            name='Gratification',
        ),
        migrations.DeleteModel(
            name='RHservice',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
        migrations.DeleteModel(
            name='Tuteur',
        ),
    ]
