# Generated by Django 3.2.4 on 2021-06-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210701_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('adresse_id', models.AutoField(primary_key=True, serialize=False)),
                ('adresse', models.CharField(max_length=64)),
                ('codePostal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=64)),
                ('pays', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='CAM',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='enseingnant',
            field=models.CharField(max_length=64),
        ),
    ]
