# Generated by Django 3.2.4 on 2021-06-30 23:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210701_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adresse',
            old_name='adresse',
            new_name='adr',
        ),
        migrations.CreateModel(
            name='Etablissements',
            fields=[
                ('etab_id', models.AutoField(primary_key=True, serialize=False)),
                ('raisonSociale', models.CharField(max_length=64)),
                ('representationLegal', models.CharField(max_length=64)),
                ('fonction', models.CharField(max_length=64)),
                ('noSiret', models.CharField(max_length=14, null=True, validators=[django.core.validators.MinLengthValidator(14)])),
                ('codeAPE', models.CharField(max_length=5, null=True)),
                ('domaineDAct', models.CharField(max_length=64)),
                ('effectif', models.IntegerField()),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresse', to='api.adresse')),
            ],
        ),
    ]
