# Generated by Django 3.2.4 on 2021-06-30 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rhservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accueilservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_Acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresse_Acc', to='api.adresse')),
                ('etab_Acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etab_Acc', to='api.etablissements')),
            ],
        ),
    ]
