# Generated by Django 3.2.4 on 2021-06-30 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_accueilservice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etablissements',
            new_name='Etablissement',
        ),
    ]
