# Generated by Django 3.2.4 on 2021-07-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_dates_stage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gratification',
            name='versement',
            field=models.CharField(choices=[('Chéque', 'Chéque'), ('Virement Bancaire', 'Virement Bancaire'), ('Espèce', 'Espèce')], default='Chéque', max_length=30),
        ),
    ]
