# Generated by Django 3.2.4 on 2021-07-01 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_gratification_versement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='IDetudiant',
            field=models.ForeignKey(default='15654896', on_delete=django.db.models.deletion.CASCADE, related_name='stage_etudiant', to='api.etudiant'),
        ),
        migrations.AlterField(
            model_name='gratification',
            name='versement',
            field=models.CharField(choices=[('Chéque', 'Chéque'), ('Virement Bancaire', 'Virement Bancaire'), ('Espèce', 'Espèce')], default='Virement Bancaire', max_length=30),
        ),
        migrations.CreateModel(
            name='Tuteurs',
            fields=[
                ('tuteur_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=64)),
                ('prenom', models.CharField(max_length=64)),
                ('numTeleph', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('fonction', models.CharField(max_length=64)),
                ('service', models.CharField(max_length=64)),
                ('disponibilite', models.CharField(choices=[('Importante', 'Importante'), ('Partielle', 'Partielle'), ('Inexistante', 'Inexistante')], max_length=30)),
                ('adresse_Tuteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresse_Tuteur', to='api.adresse')),
                ('etab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etab_Tuteur', to='api.etablissement')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stage', to='api.stage')),
            ],
        ),
    ]
