# Generated by Django 3.2.4 on 2021-07-01 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210701_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gratification',
            name='versement',
            field=models.CharField(choices=[('Chéque', 'Chéque'), ('Virement Bancaire', 'Virement Bancaire'), ('Espèce', 'Espèce')], max_length=30),
        ),
        migrations.AlterField(
            model_name='stage',
            name='IDetudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_etudiant', to='api.etudiant'),
        ),
    ]
